import { PrismaClient } from '@prisma/client';

const surahs = [
  { number: 1, name: 'Al-Fatihah', arabicName: 'الفاتحة', transliteration: 'Al-Fatihah', verseCount: 7 },
  { number: 2, name: 'Al-Baqarah', arabicName: 'البقرة', transliteration: 'Al-Baqarah', verseCount: 286 },
  { number: 3, name: 'Aali Imran', arabicName: 'آل عمران', transliteration: "Aali 'Imran", verseCount: 200 },
  { number: 4, name: 'An-Nisa', arabicName: 'النساء', transliteration: 'An-Nisa', verseCount: 176 },
  { number: 5, name: 'Al-Ma\'idah', arabicName: 'المائدة', transliteration: "Al-Ma'idah", verseCount: 120 },
  { number: 6, name: 'Al-An\'am', arabicName: 'الأنعام', transliteration: "Al-An'am", verseCount: 165 },
  { number: 7, name: 'Al-A\'raf', arabicName: 'الأعراف', transliteration: "Al-A'raf", verseCount: 206 },
  { number: 8, name: 'Al-Anfal', arabicName: 'الأنفال', transliteration: 'Al-Anfal', verseCount: 75 },
  { number: 9, name: 'At-Tawbah', arabicName: 'التوبة', transliteration: 'At-Tawbah', verseCount: 129 },
  { number: 10, name: 'Yunus', arabicName: 'يونس', transliteration: 'Yunus', verseCount: 109 },
  { number: 11, name: 'Hud', arabicName: 'هود', transliteration: 'Hud', verseCount: 123 },
  { number: 12, name: 'Yusuf', arabicName: 'يوسف', transliteration: 'Yusuf', verseCount: 111 },
  { number: 13, name: 'Ar-Ra\'d', arabicName: 'الرعد', transliteration: "Ar-Ra'd", verseCount: 43 },
  { number: 14, name: 'Ibrahim', arabicName: 'إبراهيم', transliteration: 'Ibrahim', verseCount: 52 },
  { number: 15, name: 'Al-Hijr', arabicName: 'الحجر', transliteration: 'Al-Hijr', verseCount: 99 },
  { number: 16, name: 'An-Nahl', arabicName: 'النحل', transliteration: 'An-Nahl', verseCount: 128 },
  { number: 17, name: 'Al-Isra', arabicName: 'الإسراء', transliteration: 'Al-Isra', verseCount: 111 },
  { number: 18, name: 'Al-Kahf', arabicName: 'الكهف', transliteration: 'Al-Kahf', verseCount: 110 },
  { number: 19, name: 'Maryam', arabicName: 'مريم', transliteration: 'Maryam', verseCount: 98 },
  { number: 20, name: 'Ta-Ha', arabicName: 'طه', transliteration: 'Ta-Ha', verseCount: 135 },
  { number: 21, name: 'Al-Anbiya', arabicName: 'الأنبياء', transliteration: 'Al-Anbiya', verseCount: 112 },
  { number: 22, name: 'Al-Hajj', arabicName: 'الحج', transliteration: 'Al-Hajj', verseCount: 78 },
  { number: 23, name: 'Al-Mu\'minun', arabicName: 'المؤمنون', transliteration: "Al-Mu'minun", verseCount: 118 },
  { number: 24, name: 'An-Nur', arabicName: 'النور', transliteration: 'An-Nur', verseCount: 64 },
  { number: 25, name: 'Al-Furqan', arabicName: 'الفرقان', transliteration: 'Al-Furqan', verseCount: 77 },
  { number: 26, name: 'Ash-Shu\'ara', arabicName: 'الشعراء', transliteration: "Ash-Shu'ara", verseCount: 227 },
  { number: 27, name: 'An-Naml', arabicName: 'النمل', transliteration: 'An-Naml', verseCount: 93 },
  { number: 28, name: 'Al-Qasas', arabicName: 'القصص', transliteration: 'Al-Qasas', verseCount: 88 },
  { number: 29, name: 'Al-\'Ankabut', arabicName: 'العنكبوت', transliteration: "Al-'Ankabut", verseCount: 69 },
  { number: 30, name: 'Ar-Rum', arabicName: 'الروم', transliteration: 'Ar-Rum', verseCount: 60 },
  { number: 31, name: 'Luqman', arabicName: 'لقمان', transliteration: 'Luqman', verseCount: 34 },
  { number: 32, name: 'As-Sajdah', arabicName: 'السجدة', transliteration: 'As-Sajdah', verseCount: 30 },
  { number: 33, name: 'Al-Ahzab', arabicName: 'الأحزاب', transliteration: 'Al-Ahzab', verseCount: 73 },
  { number: 34, name: 'Saba', arabicName: 'سبأ', transliteration: 'Saba', verseCount: 54 },
  { number: 35, name: 'Fatir', arabicName: 'فاطر', transliteration: 'Fatir', verseCount: 45 },
  { number: 36, name: 'Ya-Sin', arabicName: 'يس', transliteration: 'Ya-Sin', verseCount: 83 },
  { number: 37, name: 'As-Saffat', arabicName: 'الصافات', transliteration: 'As-Saffat', verseCount: 182 },
  { number: 38, name: 'Sad', arabicName: 'ص', transliteration: 'Sad', verseCount: 88 },
  { number: 39, name: 'Az-Zumar', arabicName: 'الزمر', transliteration: 'Az-Zumar', verseCount: 75 },
  { number: 40, name: 'Ghafir', arabicName: 'غافر', transliteration: 'Ghafir', verseCount: 85 },
  { number: 41, name: 'Fussilat', arabicName: 'فصلت', transliteration: 'Fussilat', verseCount: 54 },
  { number: 42, name: 'Ash-Shura', arabicName: 'الشورى', transliteration: 'Ash-Shura', verseCount: 53 },
  { number: 43, name: 'Az-Zukhruf', arabicName: 'الزخرف', transliteration: 'Az-Zukhruf', verseCount: 89 },
  { number: 44, name: 'Ad-Dukhan', arabicName: 'الدخان', transliteration: 'Ad-Dukhan', verseCount: 59 },
  { number: 45, name: 'Al-Jathiyah', arabicName: 'الجاثية', transliteration: 'Al-Jathiyah', verseCount: 37 },
  { number: 46, name: 'Al-Ahqaf', arabicName: 'الأحقاف', transliteration: 'Al-Ahqaf', verseCount: 35 },
  { number: 47, name: 'Muhammad', arabicName: 'محمد', transliteration: 'Muhammad', verseCount: 38 },
  { number: 48, name: 'Al-Fath', arabicName: 'الفتح', transliteration: 'Al-Fath', verseCount: 29 },
  { number: 49, name: 'Al-Hujurat', arabicName: 'الحجرات', transliteration: 'Al-Hujurat', verseCount: 18 },
  { number: 50, name: 'Qaf', arabicName: 'ق', transliteration: 'Qaf', verseCount: 45 },
  { number: 51, name: 'Adh-Dhariyat', arabicName: 'الذاريات', transliteration: 'Adh-Dhariyat', verseCount: 60 },
  { number: 52, name: 'At-Tur', arabicName: 'الطور', transliteration: 'At-Tur', verseCount: 49 },
  { number: 53, name: 'An-Najm', arabicName: 'النجم', transliteration: 'An-Najm', verseCount: 62 },
  { number: 54, name: 'Al-Qamar', arabicName: 'القمر', transliteration: 'Al-Qamar', verseCount: 55 },
  { number: 55, name: 'Ar-Rahman', arabicName: 'الرحمن', transliteration: 'Ar-Rahman', verseCount: 78 },
  { number: 56, name: 'Al-Waqi\'ah', arabicName: 'الواقعة', transliteration: "Al-Waqi'ah", verseCount: 96 },
  { number: 57, name: 'Al-Hadid', arabicName: 'الحديد', transliteration: 'Al-Hadid', verseCount: 29 },
  { number: 58, name: 'Al-Mujadilah', arabicName: 'المجادلة', transliteration: 'Al-Mujadilah', verseCount: 22 },
  { number: 59, name: 'Al-Hashr', arabicName: 'الحشر', transliteration: 'Al-Hashr', verseCount: 24 },
  { number: 60, name: 'Al-Mumtahanah', arabicName: 'الممتحنة', transliteration: 'Al-Mumtahanah', verseCount: 13 },
  { number: 61, name: 'As-Saff', arabicName: 'الصف', transliteration: 'As-Saff', verseCount: 14 },
  { number: 62, name: 'Al-Jumu\'ah', arabicName: 'الجمعة', transliteration: "Al-Jumu'ah", verseCount: 11 },
  { number: 63, name: 'Al-Munafiqun', arabicName: 'المنافقون', transliteration: 'Al-Munafiqun', verseCount: 11 },
  { number: 64, name: 'At-Taghabun', arabicName: 'التغابن', transliteration: 'At-Taghabun', verseCount: 18 },
  { number: 65, name: 'At-Talaq', arabicName: 'الطلاق', transliteration: 'At-Talaq', verseCount: 12 },
  { number: 66, name: 'At-Tahrim', arabicName: 'التحريم', transliteration: 'At-Tahrim', verseCount: 12 },
  { number: 67, name: 'Al-Mulk', arabicName: 'الملك', transliteration: 'Al-Mulk', verseCount: 30 },
  { number: 68, name: 'Al-Qalam', arabicName: 'القلم', transliteration: 'Al-Qalam', verseCount: 52 },
  { number: 69, name: 'Al-Haqqah', arabicName: 'الحاقة', transliteration: 'Al-Haqqah', verseCount: 52 },
  { number: 70, name: 'Al-Ma\'arij', arabicName: 'المعارج', transliteration: "Al-Ma'arij", verseCount: 44 },
  { number: 71, name: 'Nuh', arabicName: 'نوح', transliteration: 'Nuh', verseCount: 28 },
  { number: 72, name: 'Al-Jinn', arabicName: 'الجن', transliteration: 'Al-Jinn', verseCount: 28 },
  { number: 73, name: 'Al-Muzzammil', arabicName: 'المزمل', transliteration: 'Al-Muzzammil', verseCount: 20 },
  { number: 74, name: 'Al-Muddaththir', arabicName: 'المدثر', transliteration: 'Al-Muddaththir', verseCount: 56 },
  { number: 75, name: 'Al-Qiyamah', arabicName: 'القيامة', transliteration: 'Al-Qiyamah', verseCount: 40 },
  { number: 76, name: 'Al-Insan', arabicName: 'الإنسان', transliteration: 'Al-Insan', verseCount: 31 },
  { number: 77, name: 'Al-Mursalat', arabicName: 'المرسلات', transliteration: 'Al-Mursalat', verseCount: 50 },
  { number: 78, name: 'An-Naba', arabicName: 'النبأ', transliteration: 'An-Naba', verseCount: 40 },
  { number: 79, name: 'An-Nazi\'at', arabicName: 'النازعات', transliteration: "An-Nazi'at", verseCount: 46 },
  { number: 80, name: '\'Abasa', arabicName: 'عبس', transliteration: "'Abasa", verseCount: 42 },
  { number: 81, name: 'At-Takwir', arabicName: 'التكوير', transliteration: 'At-Takwir', verseCount: 29 },
  { number: 82, name: 'Al-Infitar', arabicName: 'الإنفطار', transliteration: 'Al-Infitar', verseCount: 19 },
  { number: 83, name: 'Al-Mutaffifin', arabicName: 'المطففين', transliteration: 'Al-Mutaffifin', verseCount: 36 },
  { number: 84, name: 'Al-Inshiqaq', arabicName: 'الإنشقاق', transliteration: 'Al-Inshiqaq', verseCount: 25 },
  { number: 85, name: 'Al-Buruj', arabicName: 'البروج', transliteration: 'Al-Buruj', verseCount: 22 },
  { number: 86, name: 'At-Tariq', arabicName: 'الطارق', transliteration: 'At-Tariq', verseCount: 17 },
  { number: 87, name: 'Al-A\'la', arabicName: 'الأعلى', transliteration: "Al-A'la", verseCount: 19 },
  { number: 88, name: 'Al-Ghashiyah', arabicName: 'الغاشية', transliteration: 'Al-Ghashiyah', verseCount: 26 },
  { number: 89, name: 'Al-Fajr', arabicName: 'الفجر', transliteration: 'Al-Fajr', verseCount: 30 },
  { number: 90, name: 'Al-Balad', arabicName: 'البلد', transliteration: 'Al-Balad', verseCount: 20 },
  { number: 91, name: 'Ash-Shams', arabicName: 'الشمس', transliteration: 'Ash-Shams', verseCount: 15 },
  { number: 92, name: 'Al-Layl', arabicName: 'الليل', transliteration: 'Al-Layl', verseCount: 21 },
  { number: 93, name: 'Ad-Duha', arabicName: 'الضحى', transliteration: 'Ad-Duha', verseCount: 11 },
  { number: 94, name: 'Ash-Sharh', arabicName: 'الشرح', transliteration: 'Ash-Sharh', verseCount: 8 },
  { number: 95, name: 'At-Tin', arabicName: 'التين', transliteration: 'At-Tin', verseCount: 8 },
  { number: 96, name: 'Al-\'Alaq', arabicName: 'العلق', transliteration: "Al-'Alaq", verseCount: 19 },
  { number: 97, name: 'Al-Qadr', arabicName: 'القدر', transliteration: 'Al-Qadr', verseCount: 5 },
  { number: 98, name: 'Al-Bayyinah', arabicName: 'البينة', transliteration: 'Al-Bayyinah', verseCount: 8 },
  { number: 99, name: 'Az-Zilzal', arabicName: 'الزلزلة', transliteration: 'Az-Zilzal', verseCount: 8 },
  { number: 100, name: 'Al-\'Adiyat', arabicName: 'العاديات', transliteration: "Al-'Adiyat", verseCount: 11 },
  { number: 101, name: 'Al-Qari\'ah', arabicName: 'القارعة', transliteration: "Al-Qari'ah", verseCount: 11 },
  { number: 102, name: 'At-Takathur', arabicName: 'التكاثر', transliteration: 'At-Takathur', verseCount: 8 },
  { number: 103, name: 'Al-\'Asr', arabicName: 'العصر', transliteration: "Al-'Asr", verseCount: 3 },
  { number: 104, name: 'Al-Humazah', arabicName: 'الهمزة', transliteration: 'Al-Humazah', verseCount: 9 },
  { number: 105, name: 'Al-Fil', arabicName: 'الفيل', transliteration: 'Al-Fil', verseCount: 5 },
  { number: 106, name: 'Quraysh', arabicName: 'قريش', transliteration: 'Quraysh', verseCount: 4 },
  { number: 107, name: 'Al-Ma\'un', arabicName: 'الماعون', transliteration: "Al-Ma'un", verseCount: 7 },
  { number: 108, name: 'Al-Kawthar', arabicName: 'الكوثر', transliteration: 'Al-Kawthar', verseCount: 3 },
  { number: 109, name: 'Al-Kafirun', arabicName: 'الكافرون', transliteration: 'Al-Kafirun', verseCount: 6 },
  { number: 110, name: 'An-Nasr', arabicName: 'النصر', transliteration: 'An-Nasr', verseCount: 3 },
  { number: 111, name: 'Al-Masad', arabicName: 'المسد', transliteration: 'Al-Masad', verseCount: 5 },
  { number: 112, name: 'Al-Ikhlas', arabicName: 'الإخلاص', transliteration: 'Al-Ikhlas', verseCount: 4 },
  { number: 113, name: 'Al-Falaq', arabicName: 'الفلق', transliteration: 'Al-Falaq', verseCount: 5 },
  { number: 114, name: 'An-Nas', arabicName: 'الناس', transliteration: 'An-Nas', verseCount: 6 },
];

export async function seedSurahs(prisma: PrismaClient) {
  console.log('📖 Seeding surahs...');

  for (const surah of surahs) {
    await prisma.verse.upsert({
      where: {
        surahNumber_ayahNumber: {
          surahNumber: surah.number,
          ayahNumber: 0, // 0 = metadata row
        },
      },
      update: {},
      create: {
        surahNumber: surah.number,
        ayahNumber: 0,
        arabicText: surah.arabicName,
        transliteration: surah.transliteration,
        translation: `${surah.name} (${surah.verseCount} verses)`,
      },
    });
  }

  console.log(`✅ Seeded ${surahs.length} surahs`);
}
